下面是测试numpy包是否正常安装的语句

In [1]:
import numpy as np
print(np.__version__)

2.4.2


# numpy介绍
为一个科学计算的基础包，提供数组&多维数组的快速操作工具
## ndarry核心对象
与python列表的不同：
* numpy数组创建时大小固定，在更改数组大小时会删除原数组后重新创建
* 其中所有元素的类型相同（可以创建包含Python对象的数组，此时元素大小可以不同）
* 可以更方便地处理大量数据，进行高级数学运算

### 优势
* 可以使用python风格的自然化语言，但同时保留c语言下的运行速度

### 特点
#### 向量化
定义：使用广播的形式，使得代码中不存在显式的循环/索引
* 代码更简洁
* 更接近标准数学符号
#### 广播
* 在满足一定条件的情况下，较小的数组会被“广播”到较大的数组上，从而使它们的形状兼容。
* 广播提供了一种对数组操作进行向量化处理的方法，这样循环操作便可在C语言中而非Python中执行。这样做无需对数据进行不必要的复制，通常能带来高效的算法实现。

最简单的情况下，这两个数组的形状必须完全相同，如下所示

In [12]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,2,2])
print(a+b)

[3 4 5]


NumPy的广播规则在数组形状满足特定条件时放宽了这一限制。最简单的广播示例是当一个数组与一个标量值进行运算时：

In [13]:
a = np.array([1,2,3])
b = 2
print(a+b)

[3 4 5]


其结果等效于前面那个是数组的例子。我们可以认为，在算术运算过程中，标量被拉伸成了一个与形状相同的数组。
![broadcasting_1.png](C%3A/Users/ADMINI%7E1/AppData/Local/Temp/broadcasting_1.png)

#### 下面是广播的一些性质
1. **右对齐（从最右侧开始看）**
当你比较两个数组时，NumPy 不会从开头对齐，而是像数学里的加法一样右对齐。
比如你的例子：
数组 A (3D): 256 x 256 x 3

数组 B (1D):             3

你会发现，最右边的 3 是能对上的。这说明它们在最基础的维度上是兼容的。

2. **补维度（缺少的维度视为 1）**
如果一个数组的维度比另一个少，NumPy 会在它的左边补上长度为 1 的维度。

在上面的例子中，一维数组 (3,) 在计算时会被 NumPy 视作 (1, 1, 3)。
现在形状变成了：

A: 256 x 256 x 3

B:   1 x   1 x 3

3. **拉伸原则（要么相等，要么为 1）**
这是最核心的判断标准。在对齐后的每一个位置，两个数字必须满足以下任意一个条件：

两个数字相等（比如都是 3，不用变）。

其中一个是 1（比如一个是 256，一个是 1，那么 1 就会被“拉伸”成 256）。

In [21]:
# A 是一个 4x3 的矩阵 (3 行 4 列)
A = np.ones((3, 4))

# B 是一个长度为 3 的一维数组
B = np.array([[10], [20], [30]])

# 执行加法
result = A + B

print("A 的形状:", A.shape)
print("B 的形状:", B.shape)
print("结果的形状:", result.shape)
print("\n计算结果:\n", result)

A 的形状: (3, 4)
B 的形状: (3, 1)
结果的形状: (3, 4)

计算结果:
 [[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


## numpy快速上手
### 构建矩阵
1. 使用列表构建
* ```np.array([[1,2],[3,4]])```为一个2*2的矩阵
2. 特殊的矩阵快速创建
    * 全零矩阵：```np.zeros((行, 列))```
    * 全一矩阵：```np.ones((行, 列))```
    * 单位矩阵（对角线上是1，其余为零）：```np.eye(阶数)```

In [24]:
# 通过列表构建
matrix_1 = np.array([[1,2],[3,4]])
print(matrix_1)
# 创建三阶的单位矩阵（3x3）
identity_matrix = np.eye(3)
print(identity_matrix)

# 创建全零矩阵
zeros_matrix = np.zeros((2,3))
print(zeros_matrix)

[[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 空间转换&特殊运算
1. **矩阵转置(Transpose)**：行变列，列变行
* 语法：.T

In [29]:
M = np.array([[1,2,3],[4,5,6]])
print('转置前')
print(M)
print(M.shape)
print(M.dtype)
M_T = M.T
print('转置后')
print(M_T)
print(M_T.shape)
print(M_T.dtype)

转置前
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
转置后
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
int64


### 矩阵内积的原理

### 乘法口诀：左行乘右列

假设我们要计算结果矩阵 $C$ 中第 $i$ 行、第 $j$ 列的那个数字：

1. **选定**：取出左矩阵 $A$ 的第 $i$ **行**。
2. **选定**：取出右矩阵 $B$ 的第 $j$ **列**。
3. **计算**：将它们对应位置的元素相乘，然后把所有的乘积**加在一起**。

### 举个例子
假设有两个矩阵：
$$A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, B = \begin{bmatrix} e & f \\ g & h \end{bmatrix}$$计算结果 $C = A @ B$ 的第一个元素（第一行第一列）的操作是：$$C_{11} = (a \times e) + (b \times g)$$

### 矩阵乘法&逆矩阵
1. **矩阵乘法(Matrix Multiplication)**
* 在 NumPy 中，A * B 是**逐元素相乘**（广播机制就在这里起作用）。但真正的**矩阵内积**（行乘以列）要用 @ 符号或 np.dot()。
* 规则：左矩阵的**列数**必须等于右矩阵的**行数**。即 $(m \times n) @ (n \times p) = (m \times p)$。
2. 矩阵的逆 (Inverse)
* 逆矩阵是矩阵的“倒数”
* 如果 $A \times B = I$（单位矩阵），那么 $B$ 就是 $A$ 的逆。
* 工具：使用```np.linalg.inv(A)```。
* **注意**：只有**方阵（行数=列数**才可能有逆矩阵，且**行列式不能为 0**。

In [34]:
A = np.array([[1,3,4],
              [7,8,9]])
B = np.array([[1,6],
              [9,10],
              [14,15]])
C = A @ B
print(C)
D = np.linalg.inv(C)
print(D)
print(C@D)

[[ 84  96]
 [205 257]]
[[ 0.13469602 -0.05031447]
 [-0.10744235  0.04402516]]
[[ 1.00000000e+00 -8.88178420e-16]
 [ 4.95437025e-15  1.00000000e+00]]


#### 注意！**矩阵内积**的运算中，若存在缺位，会报错！
**为什么不能广播？**
在矩阵乘法 $C = A @ B$ 中，左矩阵的列数必须和右矩阵的行数完全相等。这就像是齿轮咬合，如果左边的“齿”和右边的“槽”对不上，程序就会直接抛出 ValueError。
* 矩阵内积：是严格的几何运算，维度必须精准匹配。
* 广播机制：主要用于逐元素运算（如 +, -, *, /）。

### 存储&持久化
NumPy 的存取主要分为两种形态：**二进制（快且准）\**和\**文本（人眼可读）**。

------

### 1. 二进制存取（推荐方式 🚀）

这是 NumPy 最核心的存取方式，使用 `.npy` 格式。它会保留数组的所有信息（形状、数据类型、字节顺序），而且读写速度极快。

- **单数组保存**：使用 `np.save('filename.npy', array)`。
- **读取**：使用 `array = np.load('filename.npy')`。

> **进阶小知识**：如果你有多个矩阵（比如 A, B, C）想存进**同一个文件**，可以使用 `np.savez('data.npz', a=A, b=B)`。这就像是给矩阵打了一个压缩包 📦。

------

### 2. 文本存取（跨平台/可视化 📄）

如果你想在 Excel、记事本或其他语言（如 C++）中查看数据，就需要存为文本格式（如 `.txt` 或 `.csv`）。

- **保存**：`np.savetxt('data.csv', array, delimiter=',')`。
  - `delimiter=','` 表示用逗号分隔（CSV 的标准格式）。
- **读取**：`array = np.loadtxt('data.csv', delimiter=',')`。

------

### 3. 内存映射（处理大数据集的黑科技 🧠）

当你有一个几个 GB 甚至更大的矩阵，内存塞不下时，NumPy 允许你直接在硬盘上操作文件，而不需要全部加载到内存里。这叫 `np.memmap`。